import psycopg2
c = psycopg2.connect(dbname='Automation_DB', user='cereveate', password='cereveate@222', host='localhost')
cur = c.cursor()
cur.execute("SELECT column_name FROM information_schema.columns WHERE table_schema='historian_raw' AND table_name='historian_timeseries' ORDER BY ordinal_position")
print('historian_timeseries columns:', [r[0] for r in cur.fetchall()])
cur.execute("SELECT column_name FROM information_schema.columns WHERE table_schema='historian_raw' AND table_name='alarm_active' ORDER BY ordinal_position")
print('alarm_active columns:', [r[0] for r in cur.fetchall()])
cur.execute("SELECT DISTINCT tag_id FROM historian_raw.historian_timeseries ORDER BY tag_id LIMIT 30")
print('sample tags in historian:', [r[0] for r in cur.fetchall()])
cur.execute("SELECT tag_id, alarm_enabled, alarm_h_limit FROM historian_meta.tag_master WHERE alarm_enabled=true LIMIT 10")
print('alarm enabled tags:', cur.fetchall())
c.close()
