#!/bin/bash
# ============================================================================
# HMI Flask Application - Linux Service Installation Script
# Installs systemd service for production deployment
# Run as root or with sudo!
# ============================================================================

set -e

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "[ERROR] This script must be run as root or with sudo!"
    exit 1
fi

echo "============================================================================"
echo "HMI Flask Application - Linux Service Installer"
echo "============================================================================"
echo ""

# Configuration
SERVICE_NAME="hmi-flask"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
HMI_PATH="/home/hmi/NEW_HMI/HMI"
HMI_USER="hmi"
HMI_GROUP="hmi"

# Get the actual directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Prompt for HMI path if different
echo "[1/7] Configuration"
read -p "HMI installation path [$HMI_PATH]: " input_path
if [ ! -z "$input_path" ]; then
    HMI_PATH="$input_path"
fi

read -p "HMI service user [$HMI_USER]: " input_user
if [ ! -z "$input_user" ]; then
    HMI_USER="$input_user"
    HMI_GROUP="$input_user"
fi

# Validate HMI path
if [ ! -d "$HMI_PATH" ]; then
    echo "[ERROR] HMI path does not exist: $HMI_PATH"
    exit 1
fi

# Check if virtual environment exists
if [ ! -f "$HMI_PATH/venv/bin/gunicorn" ]; then
    echo "[ERROR] Virtual environment not found or gunicorn not installed!"
    echo "Run deploy_linux.sh first to setup the environment"
    exit 1
fi

# Create user if doesn't exist
if ! id "$HMI_USER" &>/dev/null; then
    echo "[2/7] Creating user $HMI_USER..."
    useradd -r -s /bin/bash -d "$HMI_PATH" -m "$HMI_USER"
else
    echo "[2/7] User $HMI_USER already exists"
fi

# Set ownership
echo "[3/7] Setting file ownership..."
chown -R "$HMI_USER:$HMI_GROUP" "$HMI_PATH"
chmod 755 "$HMI_PATH"

# Create logs directory with proper permissions
mkdir -p "$HMI_PATH/logs"
chown -R "$HMI_USER:$HMI_GROUP" "$HMI_PATH/logs"
chmod 755 "$HMI_PATH/logs"

# Create systemd service file
echo "[4/7] Creating systemd service file..."
cat > "$SERVICE_FILE" << EOF
# ============================================================================
# Systemd Service Unit for HMI Flask Application
# Auto-generated by install_service_linux.sh
# ============================================================================

[Unit]
Description=HMI Flask Application - Industrial Real-Time SCADA HMI
Documentation=https://github.com/yourusername/hmi-flask
After=network.target postgresql.service
Wants=postgresql.service

[Service]
Type=notify
User=$HMI_USER
Group=$HMI_GROUP
WorkingDirectory=$HMI_PATH
Environment="PATH=$HMI_PATH/venv/bin"
Environment="HMI_ENV=production"
Environment="PYTHONPATH=$HMI_PATH"

# Gunicorn with eventlet worker
ExecStart=$HMI_PATH/venv/bin/gunicorn \\
    --worker-class eventlet \\
    --workers 1 \\
    --bind 0.0.0.0:6001 \\
    --timeout 120 \\
    --keepalive 5 \\
    --log-level info \\
    --access-logfile $HMI_PATH/logs/gunicorn-access.log \\
    --error-logfile $HMI_PATH/logs/gunicorn-error.log \\
    --capture-output \\
    --pid /run/hmi-flask/hmi-flask.pid \\
    wsgi:application

# Process management
PIDFile=/run/hmi-flask/hmi-flask.pid
RuntimeDirectory=hmi-flask
Restart=always
RestartSec=10
StartLimitBurst=5
StartLimitInterval=60

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$HMI_PATH/logs

# Resource limits
LimitNOFILE=65536
LimitNPROC=512
TasksMax=512

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=hmi-flask

[Install]
WantedBy=multi-user.target
EOF

echo "[5/7] Reloading systemd daemon..."
systemctl daemon-reload

echo "[6/7] Enabling service to start on boot..."
systemctl enable $SERVICE_NAME

echo "[7/7] Starting service..."
systemctl start $SERVICE_NAME

# Wait a moment for service to start
sleep 2

# Check service status
echo ""
echo "============================================================================"
echo "Service Status:"
echo "============================================================================"
systemctl status $SERVICE_NAME --no-pager

echo ""
echo "============================================================================"
echo "Service installed successfully!"
echo "============================================================================"
echo ""
echo "Service Name: $SERVICE_NAME"
echo "Service File: $SERVICE_FILE"
echo "Working Directory: $HMI_PATH"
echo "User: $HMI_USER"
echo ""
echo "Management Commands:"
echo "  Start:   sudo systemctl start $SERVICE_NAME"
echo "  Stop:    sudo systemctl stop $SERVICE_NAME"
echo "  Restart: sudo systemctl restart $SERVICE_NAME"
echo "  Status:  sudo systemctl status $SERVICE_NAME"
echo "  Logs:    sudo journalctl -u $SERVICE_NAME -f"
echo "  Enable:  sudo systemctl enable $SERVICE_NAME"
echo "  Disable: sudo systemctl disable $SERVICE_NAME"
echo ""
echo "Application Logs: $HMI_PATH/logs/"
echo "============================================================================"
